apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
  - port: {{ .Values.registryPort }}
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
