apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: {{ .Values.databaseName }}
  POSTGRES_USER: {{ .Values.databaseUser }}
  POSTGRES_PASSWORD: {{ .Values.databasePassword }}
