apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: {{ .Values.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mountPath }}
