apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphite
  labels:
    app: graphite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphite
  template:
    metadata:
      labels:
        app: graphite
    spec:
      containers:
      - name: graphite
        image: graphiteapp/graphite-statsd:latest
        ports:
        - containerPort: 80
        - containerPort: 2003
        - containerPort: 2004
        - containerPort: 2023
        - containerPort: 2024
        volumeMounts:
        - name: graphite-data
          mountPath: /opt/graphite/storage/whisper
      volumes:
      - name: graphite-data
        persistentVolumeClaim:
          claimName: graphite
