apiVersion: v1
kind: PersistentVolume
metadata:
  name: graphite
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mountPath }}
