apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphite
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}

